### ISSUE TITLE
Rename 2FA in Microsoft Authenticator

### ISSUE THREAD

**Issue by springboynick** [born05/craft-twofactorauthentication#60] opened 2022-06-14 00:26 UTC
Good Evening,  Im having a similar issue to the user with Google Authenticator.  I have renamed my site, however it shows as CraftCMS and email address in the authenticator and not the company/website system name?

Any help would be appreciated.

Kind regards

Nick

**Comment by roelvanhintum** [comment] 2022-06-28 08:56
Duplicate of #58

**Closed as not planned by roelvanhintum** 2022-06-28 08:56 UTC
