### ISSUE TITLE
rememberedUserSessionDuration ignored?

### ISSUE THREAD

**Issue by maartenheideman** [born05/craft-twofactorauthentication#42] opened 2020-03-06 12:20 UTC
Hi,

I'll setup this plugin for a client and it works great, except that it looks like the plugin ignores 'rememberedUserSessionDuration'. This is set to 1 week for my client but when two factor auth is enabled for a user they are logged out after an hour. Even if I'll set 'userSessionDuration' to 1 week the user are logged out after 1 hour. If I'll check the cookies of the client I'll see the expire date is 7 days later. Any idea why the user is logged out so fast?

My duration settings

`// Durations
        'defaultTokenDuration' => 604800, // 1 week
        'purgePendingUsersDuration' => 0, // disable
        'verificationCodeDuration' => 604800, // 1 week
        'rememberedUserSessionDuration' => 604800, // 1 week
        'userSessionDuration' => 604800, // 1 week`

Server time setting GMT +1 Amsterdam
Craft time setting UTC + 1 Amsterdam

**Comment by roelvanhintum** [comment] 2020-03-06 14:32
@maartenheideman this sounds like an issue with sessions on your server. Even when rememberedUserSessionDuration is ignored, userSessionDuration should be used. Are you sure the same happens with the plugin disabled?

**Comment by maartenheideman** [comment] 2020-03-06 17:24
I'll checked the isVerified function and dumped $dateVerified and $minimalSessionDate. In the same order down here. The timezone looks different? Could this be the issue? 

`
object(DateTime)#371 (3) {
  ["date"]=>
  string(26) "2020-03-06 18:21:59.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(16) "Europe/Amsterdam"
}
object(DateTime)#362 (3) {
  ["date"]=>
  string(26) "2020-02-28 17:22:00.013753"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}`

**Comment by maartenheideman** [comment] 2020-03-11 20:03
I'll double checked. If a user is logged-in and completely close its browser and open the browser again their still logged-in. If the same user activates two factor authentication whit-in the front-end (create with your samples) and close its browser and open it again they are logged out. The same thing happen wit trying to login in the backend. It looks like the plugin kills the session? My plugin settings:

`'totpDelay' => null,

        'verifyFrontEnd' => true,
        'verifyBackEnd' => true,

        'forceFrontEnd' => false,
        'forceBackEnd' => false,

        // The URI we should use for 2FA ligin verification on the front-end.
        'verifyPath' => 'login/verify',

        // The URI we should use for 2FA settings (turning it on and off) on the front-end.
        'settingsPath' => 'profile/security',

        // Choose between using the whitelist or blacklist! Using both will block everything!
        // Whitelist paths that do not need 2FA. Exact path or regex. No leading slashes.
        'frontEndPathWhitelist' => [
            '*' => ['/requests/new'],
        ],
        // Blacklist paths that do need 2FA. Exact path or regex. No leading slashes.
        'frontEndPathBlacklist' => [
            '*' => [''],
        ],`

**Comment by maartenheideman** [comment] 2020-03-13 21:41
Dived a little bit deeper in the issue today. The date difference mentioned before is not the issue even after setting this the server to UTC. The problem is in the validateRequest function and then specific in $verify->isEnabled($user). That function returns false but should return true. If I'll delete this from the if else checks I'll stay logged-in else trough that part I'll logged-out. But why this only happens on the live server locally I'll didn't have that issue.

**Comment by maartenheideman** [comment] 2020-03-13 21:41
Dived a little bit deeper in the issue today. The date difference mentioned before is not the issue even after setting this the server to UTC. The problem is in the validateRequest function and then specific in $verify->isEnabled($user). That function returns false but should return true. If I'll delete this from the if else checks I'll stay logged-in else trough that part I'll logged-out. But why this only happens on the live server locally I'll didn't have that issue.

**Comment by roelvanhintum** [comment] 2020-03-24 11:31
@maartenheideman sorry for the late response. I cannot replicate this problem. Maybe something with session/cookie settings? Session until browser closes, does sound like a cookie problem.

I'm testing this with php:7.3-apache using the production ini and with the Craft required packages installed.

I did notice a config problem with the whitelist and/or blacklist:
```php
    'frontEndPathWhitelist' => [
        '*' => ['requests/new'], // Notice the removed leading slash
    ],
    // Blacklist paths that do need 2FA. Exact path or regex. No leading slashes.
    'frontEndPathBlacklist' => [
        // '*' => [''], // Disable to prevent issues
    ],
```

**Comment by maartenheideman** [comment] 2020-03-24 11:43
Thanx for your reply. When I'll comment the frontEndPathBlacklist like you do I'll get an error: `Return value of born05\twofactorauthentication\models\Settings::getFrontEndPathBlacklist() must be of the type array, null returned`.

The session closes only with two factor enabled. When two factor is disabled the session still excist. 

this are my duration settings, can this has something to do with it`?
`// Durations
        'defaultTokenDuration' => 604800, // 1 week
        'purgePendingUsersDuration' => 0, // disable
        'verificationCodeDuration' => 604800, // 1 week
        'rememberedUserSessionDuration' => 604800, // 1 week
        'userSessionDuration' => 604800, // 1 hour
`

**Comment by roelvanhintum** [comment] 2020-03-24 12:25
Your duration settings worked fine for me. No problem. With cookie/session settings i meant php / apache (or other) config.

You could comment out the entire `frontEndPathBlacklist` setting (like it isn't there). That should work for that problem.

In case none of this comes close, what PHP, Craft and plugin versions are you using?

**Comment by maartenheideman** [comment] 2020-03-24 12:40
I'am using php 7.3.14 with apache (Apache/2.4.25 (Debian)) , mariaDB 10.1 with MySQL 5.5.5, craft 3.3.7, plugin 2.4.0

Removing the complete 'frontEndPathBlacklist' setting gives the same error.

**Comment by roelvanhintum** [comment] 2020-03-24 13:16
@maartenheideman i'm using the latest craft version, but this one should also work. Are you using something like cloudfront, or are you experiencing the session issue also in a local dev environment?

I'm looking at a project right now without the blacklist without any errors. My config:
config/two-factor-authentication.php
```php
<?php
return [
    '*' => [
        'verifyBackEnd' => true,
        'forceBackEnd' => false,
    ],

    'development' => [
        'verifyBackEnd' => false,
    ],
];
```

**Comment by maartenheideman** [comment] 2020-03-25 14:56
Even after updating to craft 3.4.10.1 and in a local environment the same issue. If two factor authentication is enabled and I'll closing the browser and open it again I'am logged-out. If two factor authentication is disabled and closing the browser and open it again I'am still logged in. It must have something to do with settings of the plugin.

`    '*' => [
        // Allow a totp delay in seconds (gives the user some extra time after code expired)
        'totpDelay' => null,

        'verifyFrontEnd' => true,
        'verifyBackEnd' => true,

        'forceFrontEnd' => false,
        'forceBackEnd' => false,

        // The URI we should use for 2FA ligin verification on the front-end.
        'verifyPath' => 'login/check',

        // The URI we should use for 2FA settings (turning it on and off) on the front-end.
        'settingsPath' => 'profile/security',

        // Choose between using the whitelist or blacklist! Using both will block everything!
        // Whitelist paths that do not need 2FA. Exact path or regex. No leading slashes.
        'frontEndPathWhitelist' => [
            '*' => ['request/new'],
        ],
        // Blacklist paths that do need 2FA. Exact path or regex. No leading slashes.
        'frontEndPathBlacklist' => [
            '*' => [],
        ],
    ],`

the composer packages:
` "require": {
    "craftcms/cms": "3.4.10.1",
    "vlucas/phpdotenv": "2.4.0",
    "craftcms/redactor": "2.4.0",
    "solspace/craft-freeform": "3.5.8",
    "verbb/navigation": "1.1.13",
    "topshelfcraft/wordsmith": "3.1.1",
    "amimpact/command-palette": "3.1.4",
    "verbb/image-resizer": "2.0.6",
    "putyourlightson/craft-log-to-file": "^1.0",
    "born05/craft-twofactorauthentication": "2.4.0"
  },`

**Comment by roelvanhintum** [comment] 2020-03-30 12:35
@maartenheideman can you provide me with a copy of your project? A repo or anything? I really can't reproduce this.

**Comment by maartenheideman** [comment] 2020-03-30 14:18
Thanx for your reply I’ll send you a private email.

**Comment by maartenheideman** [comment] 2020-04-20 13:00
After updating to the newest version (3.4 +) of Craft CMS, this issue disappears and the plugin works as expected.

**Comment by maartenheideman** [comment] 2020-09-14 14:16
Thought the problem was fixed but found out that it wasn't. I'm try to understand why my client each time be logged out (frontend) after 2 hours with 2fa enabled. I thought maybe an issue in timezones? The server php & mySQL timezone configured to GMT+1 (Amsterdam). `;php_admin_value[date.timezone]` = Europe/Amsterdam. Craft is set to UTC + 2 (CEST) Europe/Amsterdam. Could that be the issue? PHP 7.3, MariaDB 10.1

# src/services/verify.php
```
public function isVerified(User $user)
    {
        $sessionId = $this->getSessionId($user);

        if (isset($sessionId)) {
            $sessionRecord = SessionRecord::findOne([
                'userId' => $user->id,
                'sessionId' => $sessionId,
            ]);

            if (isset($sessionRecord)) {
                $sessionDuration = Craft::$app->getUser()->getRemainingSessionTime();
                $minimalSessionDate = DateTimeHelper::currentUTCDateTime();
                $minimalSessionDate->sub(new DateInterval('PT' . $sessionDuration . 'S'));
                $dateVerified = DateTimeHelper::toDateTime($sessionRecord->dateVerified);

                return $dateVerified > $minimalSessionDate;
            }
        }

        return false;
    }
```
From the verify function I compared the two dates
Date time of loggin with tfa enabled = 14-09-2020 10:11:53

$dateVerified =
```
object(DateTime)#398 (3) { 
    ["date"]=> string(26) "2020-09-14 10:01:37.000000" 
    ["timezone_type"]=> int(3) 
    ["timezone"]=> string(16) "Europe/Amsterdam" 
} 
```

$minimalSessionDate =
```
object(DateTime)#389 (3) { 
    ["date"]=> string(26) "2020-09-07 08:11:53.410508" 
    ["timezone_type"]=> int(3)
    ["timezone"]=> string(3) "UTC" 
}
```

**Comment by roelvanhintum** [comment] 2020-09-15 10:36
@maartenheideman do you still have session durations of a week? In the case there is a bug with timezones not matching up, it shouldn't affect users with a difference of more than an hour. The dates checked in php seem to be ok. Php allows for different timezones in comparrisments.

I did just push a fix to make the timezones match. Can you test if that fixes it? As a version in composer you can use `dev-master`. Please do not test this on a production environment!

**Comment by maartenheideman** [comment] 2020-09-15 10:54
I'll checked the values of dateVerified and minimalSessionDate again and it looks like the timezone is matching now 👍 . Hope this solves the issue.

$dateVerified => 
```
object(DateTime)#389 (3) { 
    ["date"]=> string(26) "2020-09-15 12:48:36.000000" 
    ["timezone_type"]=> int(3) 
    ["timezone"]=> string(16) "Europe/Amsterdam" 
} 
```
$minimalSessionDate => 

```
object(DateTime)#398 (3) { 
    ["date"]=> string(26) "2020-09-08 12:49:55.897074" 
    ["timezone_type"]=> int(3) 
    ["timezone"]=> string(16) "Europe/Amsterdam" 
}
```

**Comment by roelvanhintum** [comment] 2020-09-15 11:43
Just released 2.6.2 with the fix.

**Comment by roelvanhintum** [comment] 2020-09-21 08:24
@maartenheideman did this fix the issue or are you still experiencing the short session problem?

**Comment by maartenheideman** [comment] 2020-09-21 08:47
Thanx for your reply. Unfortunately it didn't. Client still logged out after closing browser or within 2 hours. If TFA is disabled the problem disappears. Look like something with sessions. Which function is called to verify the session when opening the website?

**Comment by roelvanhintum** [comment] 2020-09-21 09:26
The starting point is (line 33 is most important) https://github.com/born05/craft-twofactorauthentication/blob/a79c55beebba08f18a3f5ec7debf50b28f36b17e/src/services/Request.php#L17-L44

Maybe the retrieval of the session id fails? https://github.com/born05/craft-twofactorauthentication/blob/a79c55beebba08f18a3f5ec7debf50b28f36b17e/src/services/Verify.php#L232-L251

It connects to `craft_twofactorauthentication_session` in the database, which depends on `craft_sessions`.

**Comment by maartenheideman** [comment] 2020-09-21 09:50
I'll just checked. After closing the browser en opening it again the session nummer upcount from 2107 to 2108 for example. The function getSessionId has a token, so that won't be the issue I gues. There is a sessionId but in the function `isVerified` SessionRecord::findOne returns null after closing browser opening again. Look like session is not authorized. If I'll dump the user `$user = Craft::$app->getUser()->getIdentity();` with a die() behind it (so it won't log me out) closing browser and opening it again, it still returns my user info.

**Comment by roelvanhintum** [comment] 2020-09-21 13:33
When you dump that is `Craft::$app->user->tokenParam` returning any value?

**Comment by maartenheideman** [comment] 2020-09-22 07:52
I'll tried that and yes it returns a token. If I'll do following. I'm doing this: 
I'm loggin in with TFA enabled. Then close my browser. Then open it again and then the the function returns a token.

```
    private function getSessionId(User $user)
    {
        $session = Craft::$app->getSession();
        $token = $session->get(Craft::$app->user->tokenParam);
        
        var_dump($token);
        die();
```

**Comment by roelvanhintum** [comment] 2020-09-22 08:12
This looks like [userSessionDuration](https://craftcms.com/docs/3.x/config/config-settings.html#usersessionduration) is set to `0`, while you have it at 604800 right?

Can you provide me with some info about your php session settings (phpinfo > `session.save_handler`, `session.cookie_lifetime`, `session.cookie_secure`, etc. )? I would like to debug this, to see where it's coming from. Do you store the session in anything like redis or the default craft settings?

**Comment by maartenheideman** [comment] 2020-09-22 09:02
this are my session duration settings in the general.php
```
        'defaultTokenDuration' => 604800, // 1 week
        'purgePendingUsersDuration' => 0, // disable
        'verificationCodeDuration' => 604800, // 1 week
        'rememberedUserSessionDuration' => 604800, // 1 week
        'userSessionDuration' => 604800, // 1 week
```

I'am not using reddis (not installed on the server), Varnish is installed but no specific rules are setup for that. And using general craft settings. The phpinfo you asked for:
```
session.save_handler = files
session.cookie_lifetime = 0
session.cookie_secure = 0
```

**Comment by roelvanhintum** [comment] 2020-09-22 14:01
@maartenheideman, i really can't reproduce this problem. I think there is some issue in your hosting setup. I tried it with the same session settings and everything worked fine. I even tried it with userSessionDuration on 0 (just released a fix for that).

**Comment by roelvanhintum** [comment] 2020-09-25 08:44
@maartenheideman thanks for all your input! The change to session variables instead of a table turned out to be simple to write. It's in 2.7.0-beta.1

**Comment by maartenheideman** [comment] 2020-09-25 10:45
I'll tried your beta but unfortunately same problem. ```Craft::$app->getSession()->get(self::SESSION_AUTH_HANDLE)``` in ```isVerified``` returns NULL after closing browser and opening again? Running craft '3.4.10.1'. If I'll return true in the function isVerified it work as expected. Also when I'll dump the session ```var_dump(Craft::$app->getSession())``` I'll can't read the custom session info 'twofactorauth_verified' that is set to true.

**Comment by roelvanhintum** [comment] 2020-09-25 14:08
Can you test this in 3.5.11.1? Is there a difference between how frontend and backend user session behave?
It works for me in firefox & chrome. Safari closes the session no matter what i do (maybe my local env?).

Explanation on the changes:
I don't try to match a session anymore. I just ask craft for the data from the current session. A new session suggests craft couldn't continue the old session, most likely because of a missing cookie.

Setting `session.cookie_secure = 0` creates cookies that live until the browser closes. Can you try to set that to something like an hour? Make sure to also check `session.gc_maxlifetime`, which cleans up sessions.

**Comment by roelvanhintum** [comment] 2020-10-05 09:07
@maartenheideman did this solve it for you?

**Comment by maartenheideman** [comment] 2020-10-05 11:46
I’ll hope I’ll have some time this week! I’ll let you know!

**Comment by maartenheideman** [comment] 2020-10-06 09:26
Just checked, setting ```session.cookie_lifetime``` to 3600 seconds keeps the user loggedin after closing browser and opening it again. What are the recommend (most safe) settings for the ```session.cookie_lifetime``` and ```session.gc_maxlifetime``` if the client wants to login once a week (from same location and device) with two factor authentication enabled.

**Comment by roelvanhintum** [comment] 2020-10-06 09:57
For one week i would say setting `session.cookie_lifetime` 604800 (60*60*24*7). ;)
`session.gc_maxlifetime` defines the time an unused session has, which restarts counting every time the session is used. This can probably be less than a week. Let's say 2 days, assuming they don't have to login for a week as long as there is less than 48 hours between using the session. This would end the session over the weekend, but would keep it alive for the entire work week.

**Closed** 2020-11-26 08:35 UTC
